### ISSUE TITLE
ES client 7.0.0-alpha1-SNAPSHOT cannot connect ES instance v6

### ISSUE THREAD

**Issue by ensecoz** [Erudika/para-search-elasticsearch#1]
Using es client v7 cannot connect es v6.
```
Caused by: java.lang.UnsupportedOperationException: REST client is yet to be supported in Elasticsearch v6.
 at com.erudika.para.search.ElasticSearchUtils.getClient(ElasticSearchUtils.java:194)
```

**Comment by ensecoz** [comment]
i checked out source code and try to update dependency back to 6.3.0-SNAPSHOT but get another error.

Not sure why LUCENE_7_3_1 is there. Something wrong about the versioning.

```
Caused by: java.lang.NoSuchFieldError: LUCENE_7_3_1
 at org.elasticsearch.Version.<clinit>(Version.java:168)
```

**Comment by albogdano** [comment]
The master branch is unstable, don't use it. You should wait until ES 6.3.0 is released after which I'll release an updated version of the plugin.
